name = "OliveMarkdown"
uuid = "e20f13e9-ec62-4716-8935-0d6a9c8994c4"
authors = ["emmac <emmaccode@gmail.com>"]
version = "0.1.0"

[deps]
Olive = "724ecaf6-c7a0-4c22-b37e-0bb7b4193da8"

[compat]
Olive = "0.2.3"
julia = "1.8"


